steps:
  # See https://github.com/GoogleCloudPlatform/cloud-builders/issues/26
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git config -f .git/config submodule.google_cyanobyte.url https://source.developers.google.com/p/cyanobyte-235018/r/github_google_cyanobyte &&
      git config -f .gitmodules submodule.google_cyanobyte.url https://source.developers.google.com/p/cyanobyte-235018/r/github_google_cyanobyte &&
      git submodule init &&
      git submodule update
  id: Bash it
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args: ['-c', 'ls -R']
  id: Setup Docsy theme
  # Setup https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/hugo
- name: gcr.io/$PROJECT_ID/hugo
  dir: docs
  args: []
  id: Generate HTML
  # Setup https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/firebase
- name: gcr.io/$PROJECT_ID/firebase
  args: ['deploy']
  dir: docs
  id: Deploy to Firebase
